# Site
repository: sproogen/jameswgrant
favicon: images/favicon.ico

version: 2

# Personal info
name: Carter Haid
title: Security Engineer 
email: carter.c.haid@gmail.com

# Social links
twitter_username: icansecurethat
github_username:  icansecurethat
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: carterhaid
# pinterest_username:
# youtube_username:

additional_links:
- title: Dark link
  icon: fa-solid fa-terminal
  url: https://github.com/icansecurethat

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, I'm Carter Haid — Information Security Engineer at Northeast Bank.


  
  I specialize in building secure, high-performance systems that align with business goals and compliance standards. With a strong foundation in cybersecurity and hands-on experience across identity, infrastructure, and vulnerability management, I bring a practical, security-first mindset to every project.

 
  I thrive in dynamic environments and enjoy tackling complex challenges that demand both technical depth and strategic thinking.



  Core technologies and tools I work with:
  
  <mark>Rapid7 Suite</mark>,
  <mark>Microsoft Entra ID</mark>,
  <mark>Python</mark>,
  <mark>Git &amp; GitHub</mark>,
  <mark>Fortinet Security Suite</mark>,
  <mark>Windows/Linux Server</mark>,
  <mark>Cisco Networking</mark>,
  <mark>Power Platform</mark>,
  and <mark>NetBox</mark>


content:
  - title: Certifications
    layout: text
    content: | # this will include new lines to allow paragraphs
      Security Certifications: 
        - <mark>CompTIA CYSA+</mark>
        - <mark>Cisco CCNA</mark>

      Vulnerability Management Certifications:
        - <mark>Rapid7 InsightVM Certified Administrator</mark>
        - <mark>Rapid7 InsightIDR Certified Specialist</mark>

      Cloud Certifications:
        - <mark>AWS CCP</mark>
        
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Northeast Bank
        sub_title: Information Security Engineer
        link: Northeastbank.com
        caption: August 2024 - Present
        description: |

      - layout: left
        border: weak
        title: Northeast Bank
        sub_title: Information Security Analyst
        link: Northeastbank.com
        caption: July 2022 - August 2024
        description: |

      - layout: left
        border: weak
        title: Tinder
        sub_title: Security Engineering Intern
        link: Tinder.com
        caption: May 2021 - December 2021
        description: |

      - layout: left
        border: weak
        title: Tyler Technologies
        sub_title: Information Security Intern
        link: Tylertech.com
        caption: May 2020 - September 2020
        description: |

      - layout: left
        border: weak
        title: Northeast Bank
        sub_title: Information Technology Intern
        link: Northeastbank.com
        caption: May 2019 - April 2020
        description: |

      - layout: left
        border: weak
        title: The Jackson Laboratory
        sub_title: Network Engineering Intern
        link: Jax.org
        caption: May 2018 - August 2018
        description: |

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
